name: 🤖 Check Difference

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  files:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
    
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ${{ github.workspace }}/bin

      - name: download go-jsonschema
        run: make go-jsonschema

      - name: check diff
        run: |
          make generate
          git add --intent-to-add internal
          git diff --exit-code internal

  gomod:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
    
      - uses: actions/setup-go@v4
        with:
          go-version: stable

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ${{ github.workspace }}/bin

      - name: run go mod tidy
        run: go mod tidy

      - name: check diff
        run: |
          git add --intent-to-add go.mod go.sum
          git diff --exit-code go.mod go.sum
